services:
  - type: web
    name: shadowfolio
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SEARCH_ENGINE_ID
        sync: false
      - key: PORT
        value: 5000
    autoDeploy: true
